from ImReader import *
from LineDetector import *
from ShapeDetector import *

if __name__ == "__main__":

 #   NewImage = ImReader("../Resources/easy/e1.jpg")
 #   NewDetector = LineDetector(NewImage)
 #   NewDetector.showLinesImage()
 #   print(len(NewDetector.lines))
 #   NewImage = ImReader("../Resources/easy/e2.jpg")
 #   NewDetector = LineDetector(NewImage)
 #   NewDetector.showLinesImage()
 #   print(len(NewDetector.lines))
 #   NewImage = ImReader("../Resources/easy/e3.jpg")
 #   NewDetector = LineDetector(NewImage)
 #   NewDetector.showLinesImage()
 #   print(len(NewDetector.lines))
 #   NewImage = ImReader("../Resources/easy/e4.jpg")
 #   NewDetector = LineDetector(NewImage)
 #   NewDetector.showLinesImage()
 #   print(len(NewDetector.lines))
 #   NewImage = ImReader("../Resources/easy/e5.jpg")
 #   NewDetector = LineDetector(NewImage)
 #   NewDetector.showLinesImage()
 #   print(len(NewDetector.lines))


    NewImage = ImReader("../Resources/medium/m1.jpg")
    NewDetector = LineDetector(NewImage)
    NewDetector.showNoLinesImage()
    NewImage = ImReader("../Resources/medium/m2.jpg")
    NewDetector = LineDetector(NewImage)
    NewDetector.showNoLinesImage()
    NewImage = ImReader("../Resources/medium/m3.jpg")
    NewDetector = LineDetector(NewImage)
    NewDetector.showNoLinesImage()
    NewImage = ImReader("../Resources/medium/m4.jpg")
    NewDetector = LineDetector(NewImage)
    NewDetector.showNoLinesImage()
    NewImage = ImReader("../Resources/medium/m5.jpg")
    NewDetector = LineDetector(NewImage)
    NewDetector.showNoLinesImage()
    NewImage = ImReader("../Resources/medium/m6.jpg")
    NewDetector = LineDetector(NewImage)
    NewDetector.showNoLinesImage()
    NewImage = ImReader("../Resources/medium/m7.jpg")
    NewDetector = LineDetector(NewImage)
    NewDetector.showNoLinesImage()